name: Create nugetfile with proper credentials

on:
  workflow_call:
    inputs:
      nuget-source:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string

jobs:
  reusable-nugetconfig-generation:
    runs-on: dappradar-runner
    #runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Test version (BEFORE)
        run: |
          dotnet --version
          which dotnet

      - name: Setup dotnet env
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{inputs.dotnet-version}}
        env:
          DOTNET_INSTALL_DIR: "~/dotnet"

      - name: Test version (AFTER)
        run: |
          dotnet --version
          which dotnet
          
      - name: Generate nuget file
        run: dotnet new nugetconfig

      - name: Setup nuget source
        run: dotnet nuget add source ${{ inputs.nuget-source }} -n github -u ${{ secrets.GH_USER_NAME }} -p ${{ secrets.GH_TOKEN }} --store-password-in-clear-text --configfile nuget.config

      - name: List soruces for nuget
        run: dotnet nuget list source

      - name: cat nuget.config
        run: cat nuget.config

      - uses: actions/upload-artifact@v2
        with:
          name: nugetconfig
          path: nuget.config

